version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fast-api-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1b8c1uopbpobd"
s3_prefix = "fast-api-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
